### ISSUE TITLE
Use Franklin for the site

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLabs/julialabs.github.io#11]
It would be nice to transition the site to Franklin. @tlienart said he would be happy to help.

**Comment by tlienart** [comment]
here: https://tlienart.github.io/julialabs/
source: https://github.com/tlienart/julialabs

**Comment by tlienart** [comment]
a few dead links:

```
├─BROKEN─ http://pcl.intel-research.net/ (ERRNO_ENOTFOUND)
├─BROKEN─ https://www.sysml.cc/doc/37.pdf (BLC_UNKNOWN)
├─BROKEN─ http://web.stanford.edu/~poulson/ (HTTP_404)
├─BROKEN─ https://datascience.nih.gov/bd2k (HTTP_404)
├─BROKEN─ http://www.darpa.mil/program/xdata (HTTP_404)
├─BROKEN─ http://runpeng.mit.edu/ (HTTP_404)
├─BROKEN─ http://math.mit.edu/%7Eajt/ (HTTP_403)
├─BROKEN─ http://www.mit.edu/%7Ehuchette (HTTP_404)
├─BROKEN─ http://orc.scripts.mit.edu/people/student.php?name=yeesian (HTTP_404)
├─BROKEN─ http://www.mit.edu/%7Emlubin/ (HTTP_404)
├─BROKEN─ http://isnweb.mit.edu/ (ERRNO_ENOTFOUND)
├─BROKEN─ https://superurop.eecs.mit.edu/ (BLC_UNKNOWN)
```

**Comment by ViralBShah** [comment]
I've invited @tlienart for admin access.

What steps need to be taken to complete the migration?

**Comment by tlienart** [comment]
* have someone check superficially that things look ok (I checked on FF, safari, desktop and mobile so should be ok)
* how is the site deployed at the moment? 

Re (2) it's easy to set up a GA to generate the site on gh-pages. Can whatever system you're using subsequently be adapted to deploy that branch? (that would be similar to the JuliaLang website setup)

**Comment by ViralBShah** [comment]
Just to github pages like all others. You can see it in the settings. @ranjanan Can you help check the new thing looks ok, and aid with  migration?
