### ISSUE TITLE
Proposed outline for new julialab website

### ISSUE THREAD

**Issue by alanedelman** [JuliaLabs/julialabs.github.io#17]
lab picture of humans in the lab + 1 corgi + ...
 
 top: featured videos     ted talk + diegelman + ranjan's-save-animals + sciml as a software problem
 (parallelism/accelerators)

boxes with current research / grants (start date)

current people with individual photos (round pictures are nice like cmu https://www.cmu.edu/aced/)

**Comment by tjdiamandis** [comment]
Videos:
Ted talk: https://www.youtube.com/watch?v=qGW0GT1rCvs
Diegelman talk: https://www.youtube.com/watch?v=tQpqsmwlfY0
SciML as a software problem: https://www.youtube.com/watch?v=XRJ-rtP2fVE&t=11s

Featured News Content:
Circuitspace (Ranjan) -- get GIF from this: https://maps.tnc.org/migrations-in-motion/#4/32.29/-101.51
Space weather: https://news.mit.edu/2020/mit-led-team-will-develop-software-forecast-space-storms-0910

**Comment by alanedelman** [comment]
assignments

@tjdiamandis theo - videos
emmanuel - photos of current people/ and maybe julialab alumni (what they are doing now) / and maybe affiliates 
flemming  - grants, cool one sentence, image/grant, press release links

**Comment by ChrisRackauckas** [comment]
https://discourse.julialang.org/t/julia-lab-and-sciml-website-work/63956 wait and see.

**Comment by tlienart** [comment]
re discourse post, if you folks want to stick with Franklin, I'll be glad to lend a hand to whoever picks this up; on the design front just going with a css framework like bootstrap would already go a long way to make the website(s) look more modern/pro and wouldn't be too much effort.

**Comment by ChrisRackauckas** [comment]
Sticking with Franklin would be good. Some nice template ideas:

https://www.cmu.edu/aced/sciML.html
Something that incorporates video: https://www.meche.engineering.cmu.edu/directory/bios/viswanathan-venkat.html
http://acl.mit.edu/projects is interesting but not great
http://tensor-compiler.org/

**Comment by tlienart** [comment]
:+1: it's actually fairly easy to copy the design of a given webpage (eg we could do the CMU website pretty much 1-1 if you guys don't care about having an identical website) it's more work to come up with an original design you like. For the latter, best is probably to come up with 3-4 slides showing (1) a sketch of the landing page and (2) a sketch for the other pages.

Either way I'd be happy to get you started.

**Comment by emmanuellujan** [comment]
Photos of JuliaLab members, alumni, and collaborators: https://drive.google.com/drive/folders/1fhXML9aaAbdFtayTWk6ydUBRWqedrfeY?usp=sharing
This folder has photos of 47 people but is still incomplete. I will complete it very soon.

**Comment by FHoltorf** [comment]
Document for collecting information on grants (cool one sentence descriptions, image/grant, press release links, etc.): 
https://docs.google.com/document/d/1ATmmd7gLF6CwMtc8tHwBbQ2KxZIaP5lAGP6DlVPMJQ8/edit?usp=sharing

I didn't find much or any information on a few (smaller) grants. Every "cool sentence" in the document so far was drafted by me, so other suggestions and improvements are encouraged and very appreciated! Also if anyone has a cool image related to a project (for example from a publication) or other interesting information, please feel free to add it.

**Comment by emmanuellujan** [comment]
List of Julia Lab members, alumni, and collaborators: https://docs.google.com/spreadsheets/d/1lK13L5-5DJG2G6272SH0BVkZu5Vun_aUbXjg6jRwbS0/edit#gid=0
I am completing this list.

**Comment by emmanuellujan** [comment]
- I created a branch with the new website (https://github.com/JuliaLabs/julialabs.github.io/tree/new-website).
- Link to a demo: https://www.emmanuellujan.com/julialab-website-test/
- TODO:
    - Update the table with people's information.(https://github.com/JuliaLabs/julialabs.github.io/blob/new-website/_assets/people.csv)
    - Add information about research/grants (https://github.com/JuliaLabs/julialabs.github.io/blob/new-website/research-grants.md, but maybe we can create a csv)
    - Find missing photos (https://github.com/JuliaLabs/julialabs.github.io/tree/new-website/_assets/people)
    - Resize photos to avoid odd aspect ratios

**Comment by ChrisRackauckas** [comment]
The lab list seems overly broad. Vijay definitely was never Julia Lab. Nor Deniz. Are you putting external collaborators there as well? That should probably be separate. And alums, like Dan and Jiahao, shouldn't be in the list of those who are here right now. I think the front page should just be the current members.

The following are all alums:

Chris de Graaf
Research Software Engineer

Dan Girshovich
Research Software Engineer

James Schloss
Research Software Engineer

Diogo Netto
Undergraduate

Shawn Im
Undergraduate


David Kaplow
Undergraduate

Benjamin Urquhart
Undergraduate

**Comment by FHoltorf** [comment]
With the research/grants section as in the demo, do we want to stick with the idea of having only a nice picture, a "cool" sentence and links to press releases etc. for each project? If so, I will prepare a PR with the info from here https://docs.google.com/document/d/1ATmmd7gLF6CwMtc8tHwBbQ2KxZIaP5lAGP6DlVPMJQ8/edit?usp=sharing to the repo of @emmanuellujan and question people on the projects so we can fill in the blanks.

The demo looks like we may want to consider to add a little abstract for each project instead (or additionally)? Should I collect drafts for those instead (or as well)?

**Comment by emmanuellujan** [comment]
Hi!,

> The lab list seems overly broad. Vijay definitely was never Julia Lab. Nor Deniz.

 In the current Julia Lab website Vijay is in "Collaborators" section, and Deniz is in "Alumni" section. Is this information correct?

> Are you putting external collaborators there as well? 

Yes, because "Collaborators" section is present on the current website

> That should probably be separate.

People is located in different sections according to their role (see "Role" column in [people.csv](https://github.com/JuliaLabs/julialabs.github.io/blob/new-website/_assets/people.csv))

> And alums, like Dan and Jiahao, shouldn't be in the list of those who are here right now.

I moved Dan Girshovich to Alumni section. Jiahao Chen was already in Alumni section.

> I think the front page should just be the current members.

What do you think about adding the current members and images about the projects in the front page?

> 
> The following are all alums:
> 
> Chris de Graaf
> Research Software Engineer
> 
> Dan Girshovich
> Research Software Engineer
> 
> James Schloss
> Research Software Engineer
> 
> Diogo Netto
> Undergraduate
> 
> Shawn Im
> Undergraduate
> 
> David Kaplow
> Undergraduate
> 
> Benjamin Urquhart
> Undergraduate

Great, I updated people.csv. Thanks for the information!

**Comment by emmanuellujan** [comment]
Hi!

> With the research/grants section as in the demo, do we want to stick with the idea of having only a nice picture, a "cool" sentence and links to press releases etc. for each project? 
 
I think title+photo+description+links for each project is enough for a first version of the research/grants section. Then we can improve it if necessary.

> If so, I will prepare a PR with the info from here https://docs.google.com/document/d/1ATmmd7gLF6CwMtc8tHwBbQ2KxZIaP5lAGP6DlVPMJQ8/edit?usp=sharing to the repo of @emmanuellujan and question people on the projects so we can fill in the blanks.

Please, add the content in this branch: https://github.com/JuliaLabs/julialabs.github.io/tree/new-website, then I will update the demo.

> 
> The demo looks like we may want to consider to add a little abstract for each project instead (or additionally)? Should I collect drafts for those instead (or as well)?

I think it is convenient to have a brief-description/abstract of each project.

Thanks!

**Comment by ChrisRackauckas** [comment]
@vchuravy can I get admin here? I want to fix this whole "default to dev" branch madness and not deploy to master...

**Comment by ChrisRackauckas** [comment]
@tlienart can you help us out? It just can't push to index because of this silly default to dev stuff. Other pages are fine

https://julialabs.github.io/people/
https://julialabs.github.io/research-grants/

**Comment by ChrisRackauckas** [comment]
@emmanuellujan 

SWIFT:

![image (2)](https://user-images.githubusercontent.com/1814174/140425063-50d89c41-2525-4b3b-bda6-b7e1481dd95f.png)

or


![image (2)](https://user-images.githubusercontent.com/1814174/140425197-d7b75c9f-8897-44b9-90b0-0ea853fb9d8d.png)


JuliAD4ESM: 

![image](https://user-images.githubusercontent.com/1814174/140424595-7f0b38b4-5280-4223-9795-6c4011742e2f.png)

PowerSciML:

![image](https://user-images.githubusercontent.com/1814174/140424890-95476e5a-3a04-4b0c-8fa0-495d4b65fc4f.png)

Creative commons licensed

EPIUQ

![image](https://user-images.githubusercontent.com/1814174/140425287-060101e2-b24c-403f-9bdf-84dd5766c879.png)

**Comment by ChrisRackauckas** [comment]
PAPPA:

<img width="478" alt="Capture" src="https://user-images.githubusercontent.com/1814174/140425467-b9ff06cb-95a7-41c1-be85-b084adb5fc57.PNG">

Ford:

![image](https://user-images.githubusercontent.com/1814174/140426132-5d9f9863-44fe-4caf-b92f-2fb5260d45f7.png)

**Comment by tlienart** [comment]
> @tlienart can you help us out? It just can't push to index because of this silly default to dev stuff. Other pages are fine
> 
> https://julialabs.github.io/people/ https://julialabs.github.io/research-grants/

you're now admin; I'm happy to help you guys out with any specific issue you might need help with!

**Comment by ChrisRackauckas** [comment]
Released, thanks. Will close and following issues will be more directed. Now it's the standard master + gh-pages flow.
