### ISSUE TITLE
More grants images

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLabs/julialabs.github.io#32]
Could I get help with these two? @emmanuellujan 

SciMLPharma: 
![image](https://user-images.githubusercontent.com/1814174/141107123-44118da7-c70e-477b-a1c3-47f57406709a.png)

Neuroblox: ![Capture](https://user-images.githubusercontent.com/1814174/141107049-5aaab525-f618-4570-9023-e60de76fcd48.PNG)

**Comment by emmanuellujan** [comment]
Done :)
