### ISSUE TITLE
web visual featuring Julia@MIT

### ISSUE THREAD

**Issue by alanedelman** [JuliaLabs/julialabs.github.io#7]
Can we put somewhere high up a collage perhaps with the visual appeal of https://juliacomputing.com/case-studies/
which covers mit researchers with face and graphic and link to news articles and /or research

Juan Pablo
Steven 
Robin 
Dehann
http://news.mit.edu/2018/adding-power-choices-reduces-cost-risk-carbon-free-electricity-0906
Jeremy
John 
etc?

**Comment by alanedelman** [comment]
MIT News
http://news.mit.edu/2018/adding-power-choices-reduces-cost-risk-carbon-free-electricity-0906
http://news.mit.edu/2018/mit-developed-julia-programming-language-debuts-juliacon-0827
http://news.mit.edu/2017/four-from-mit-named-ieee-fellows-1207
http://news.mit.edu/2016/juliacon-draws-global-users-of-dynamic-programming-language-0718
http://news.mit.edu/2014/high-performance-computing-programming-ease

mit sloan news
http://mitsloan.mit.edu/newsroom/press-releases/jump-a-modeling-language-with-roots-at-mit-sloan-achieves-a-new-milestone-in-the-open-source-community-with-its-acceptance-as-a-numfocus-sponsored-project/
http://mitsloan.mit.edu/newsroom/articles/creating-better-bus-routes-with-algorithms/

**Comment by ViralBShah** [comment]
Maybe a newer version of #1.

**Comment by ChrisRackauckas** [comment]
Overhauled.
