### ISSUE TITLE
some content updates

### ISSUE THREAD

**Issue by shashi** [JuliaLabs/julialabs.github.io#9]
from slack:

- [x] Chris R, Shashi, David and Ranjan should be added as a current members
- [ ] Past rseach should move off into a separate tab, and focus on current research. All front page material should be updated (or deleted)
- [ ] It might be good to just say "organizations spawned from Julia Lab reserach" and list JuliaDiff, JuMP, SciML, etc. and link to the webpages
- [ ] it would be good to get a youtube playlist.
- [x] "over ten million" downloads

**Comment by gnadt** [comment]
Add: Albert Gnadt (PhD Student), Collin Warner (Undergraduate)

**Comment by ChrisRackauckas** [comment]
A major overhaul occurred.
